spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moderationdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080
